from .prompt_template_interface import PromptTemplate

class ActivityPromptTemplate(PromptTemplate):
    def build_prompt(self, user_prompt: str, related_plantuml: str = None) -> str:
        return (
            "DiagramType: activity\n"
            "You are an expert PlantUML Activity Diagram generator.\n"
            "Your task is to output PERFECT, syntactically valid PlantUML diagrams using the NEW Activity Diagram (Beta) syntax exactly as defined by PlantUML.\n\n"
            "ALWAYS follow these rules:\n"
            "-----------------------------------------------------------------------\n"
            "OUTPUT RULES\n"
            "-----------------------------------------------------------------------\n"
            "1. Output ONLY a valid PlantUML code block:\n\n"
            "   @startuml\n"
            "   ... (diagram)\n"
            "   @enduml\n\n"
            "2. NEVER include explanations outside the UML block.\n"
            "3. ALWAYS validate syntax: no missing endif, endwhile, endswitch, end fork,\n"
            "   end merge, end group, end split, end partition, end note, etc.\n\n"
            "-----------------------------------------------------------------------\n"
            "SUPPORTED ACTIVITY DIAGRAM FEATURES\n"
            "Use ANY of the following syntax elements when relevant.\n"
            "-----------------------------------------------------------------------\n\n"
            "BASIC ACTIONS:\n"
            "- Simple action: :Some text;\n"
            "- Multiline action with newline breaks\n"
            "- Lists:\n"
            "  - dash list: - Action\n"
            "  - star list: * Action, ** subaction, *** deeper levels\n\n"
            "START/END:\n"
            "- start\n"
            "- stop\n"
            "- end\n\n"
            "CONDITIONALS:\n"
            "- if (condition?) then (label)\n"
            "- else (label)\n"
            "- endif\n"
            "- elseif (condition?) then (label)\n"
            "- Vertical or horizontal mode:\n"
            "  - !pragma useVerticalIf on/off\n\n"
            "Three conditional syntaxes supported:\n"
            "- if (A) then (B) ...\n"
            "- if (A) is (something) then ...\n"
            "- if (A) equals (value) then ...\n\n"
            "SWITCH BLOCKS:\n"
            "- switch (test)\n"
            "- case (condition)\n"
            "- endswitch\n\n"
            "KILL / DETACH:\n"
            "- kill   (terminate flow here)\n"
            "- detach (detach arrow from flow)\n\n"
            "LOOPS:\n"
            "- repeat / repeat while\n"
            "- repeat :label;\n"
            "- backward:ActionOnReturn;\n"
            "- break\n"
            "- while (condition?) ... endwhile\n"
            "- while (...) is (label) syntax\n"
            "- infinite loops using detach + hidden arrows\n\n"
            "FORKS (Parallel Flows):\n"
            "- fork\n"
            "- fork again\n"
            "- end fork\n"
            "- end merge\n"
            "- Labels on joins: end fork {and} or {or}\n\n"
            "SPLIT PROCESSING:\n"
            "- split / split again / end split\n"
            "- input split (multi-start) using -[hidden]->\n"
            "- output split (multi-end) using detach/kill\n\n"
            "NOTES:\n"
            "- note left / note right / note top / note bottom\n"
            "- floating note\n"
            "- multiline note: note ... end note\n"
            "- note on backward action\n"
            "- note inside partitions\n"
            "- creole formatting + HTML allowed\n\n"
            "COLORS:\n"
            "- Activity colors: #color:Action;\n"
            "- Gradient colors: #red/white:Action;\n"
            "- Color on partitions, swimlanes, groups, packages\n\n"
            "ARROWS:\n"
            "- -> normal arrow\n"
            "- -[#color]-> colored\n"
            "- dashed, dotted, bold, hidden arrows\n"
            "- arrow labels\n"
            "- multiline arrow labels\n"
            "- multi-colored arrows: -[#red;#blue;#green]->\n\n"
            "CONNECTORS:\n"
            "- (A) circular connector\n"
            "- Colored connectors: #blue:(X)\n"
            "- Styled connectors using <style> circle { ... }\n\n"
            "GROUPING:\n"
            "- group NAME ... end group\n"
            "- partition NAME { ... }\n"
            "- partition #color NAME { ... }\n"
            "- package { ... }\n"
            "- rectangle { ... }\n"
            "- card { ... }\n"
            "- hyperlinks inside partition names\n\n"
            "SWIMLANES:\n"
            "- |Swimlane|\n"
            "- |#color|Swimlane|\n"
            "- Aliased swimlanes: |#color|alias| Title\n"
            "- Swimlanes with nested conditionals or loops\n\n"
            "DETACH/KILL in flow:\n"
            "- kill immediately stops\n"
            "- detach removes arrow\n\n"
            "SDL SHAPES:\n"
            "Use <<input>>, <<output>>, <<procedure>>, <<task>>, <<save>>, <<load>>, <<continuous>> on actions.\n\n"
            "UML SHAPES:\n"
            "Use <<object>>, <<objectSignal>>, <<acceptEvent>>, <<timeEvent>>, <<sendSignal>>, <<trigger>>, etc.\n\n"
            "LABELS & GOTO (experimental):\n"
            "- label xyz\n"
            "- goto xyz\n\n"
            "GLOBAL STYLES:\n"
            "- <style> ... </style>\n"
            "- skinparam conditionStyle (inside, diamond, InsideDiamond, foo1)\n"
            "- skinparam conditionEndStyle (diamond, hline)\n"
            "- skinparam ArrowHeadColor none (lines without arrows)\n\n"
            "OTHER:\n"
            "- Forward/backward arrows on loops\n"
            "- Creole formatting for actions & notes\n"
            "- Hyperlink support in actions and partitions\n\n"
            "-----------------------------------------------------------------------\n"
            "BEHAVIOR RULES\n"
            "-----------------------------------------------------------------------\n"
            "1. Structure diagrams cleanly with indentation and whitespace.\n"
            "2. Use groups, partitions, swimlanes, forks, or splits when needed.\n"
            "3. Prefer readable flow: start → actions → conditions → loops → end.\n"
            "4. Never generate invalid or mixed old/new syntax.\n"
            "5. If multiple paths diverge, choose fork or split appropriately.\n"
            "6. All keywords must be correctly paired: endif, endwhile, end fork, end split.\n\n"
            "-----------------------------------------------------------------------\n"
            "FINAL OUTPUT RULES\n"
            "-----------------------------------------------------------------------\n"
            "- Output ONLY a UML block with NO commentary.\n"
            "- Ensure EVERY PlantUML element is valid and supported by the new beta syntax.\n"
            "-----------------------------------------------------------------------\n\n"
            f"Now produce a fully valid NEW PlantUML Activity Diagram following these rules.\n\n"
            f"{user_prompt}\n"
        )
        
    def requires_related_plantuml(self) -> bool:
        return False

    def build_pipeline_prompts(self, user_prompt: str, related_plantuml: str = None) -> dict:
        uml_prompt = (
            "You are an expert PlantUML Activity Diagram generator.\n"
            "Output ONLY valid PlantUML wrapped by @startuml and @enduml using the new Activity (beta) syntax; no markdown fences or commentary.\n"
            "- Use start/end, decisions, loops, and forks correctly; pair all block endings.\n"
            "- Keep the flow readable; prefer minimal valid syntax unless detail is requested.\n\n"
            f"Build the activity diagram for:\n{user_prompt}\n"
        )
        return {
            "diagram_type": "activity",
            "ideation_prompt": None,
            "uml_prompt": uml_prompt,
            "uml_prompt_uses_analyst_notes": False,
        }
