from __future__ import annotations

from app.infrastructure.internal.agent_factory import AgentFactory


class MultiAgentOrchestrator:
    """
    Infrastructure concern that coordinates multiple AI agents.
    Lives in the infrastructure layer to keep application/domain free of agent wiring.
    """

    def __init__(self, initial_agent_type="openai", reviewer_agent_type="gronk", rounds=1):
        self.initial_agent_type = initial_agent_type
        self.reviewer_agent_type = reviewer_agent_type
        self.rounds = rounds

        self.initial_agent = AgentFactory.create_agent(initial_agent_type)
        self.reviewer_agent = AgentFactory.create_agent(reviewer_agent_type)

    def orchestrate(self, user_prompt: str) -> str:
        print(f"🔵 Starting Multi-Agent Orchestration | Rounds: {self.rounds}")

        current_output = self.initial_agent.prompt_to_uml(user_prompt)
        print(f"✅ Initial UML generated by {self.initial_agent_type}")

        for round_num in range(1, self.rounds + 1):
            print(f"🌀 Round {round_num} Review and Improvement")

            reviewer_prompt = (
                "You are reviewing a UML design based on a user request.\n"
                "Here is the original user prompt:\n"
                f"{user_prompt}\n\n"
                "Here is the UML they generated:\n"
                f"{current_output}\n\n"
                "Suggest concrete improvements or missing elements. "
                "List your suggestions clearly without re-generating the UML."
            )
            suggestions = self.reviewer_agent.generate(reviewer_prompt)
            print(f"📝 Reviewer {self.reviewer_agent_type} suggested improvements.")

            improvement_prompt = (
                "Please improve the following UML based on the review suggestions.\n\n"
                "Original User Prompt:\n"
                f"{user_prompt}\n\n"
                "Current UML:\n"
                f"{current_output}\n\n"
                "Suggestions to apply:\n"
                f"{suggestions}\n\n"
                "Return the improved UML in PlantUML format only."
            )
            current_output = self.initial_agent.prompt_to_uml(improvement_prompt)
            print(f"🔧 Applied reviewer suggestions in Round {round_num}.")

        print(f"🏁 Final UML after {self.rounds} round(s) completed.")
        return current_output
