from __future__ import annotations
from typing import Protocol, Optional

class IInfrastructureService(Protocol):
    def generate_prompt(self, prompt: str) -> str: ...
    def prompt_to_uml(self, prompt: str, agent_type: Optional[str] = None, diagram_type: Optional[str] = None, pipeline_prompts: Optional[dict] = None, pipeline_models: Optional[dict] = None) -> str: ...
    def explain_model(self, model: str) -> str: ...
    def render_model(self, model: str) -> str: ...
    def refine_model(self, model: str, feedback: str, agent_override=None) -> str: ...
    def generate_code(self, model: str, agent_type: Optional[str] = None) -> str: ...
    def cleanup_old_models(self) -> None: ...
    def retrieve(self, pk: str, sk: str) -> str: ...
    def save_model(self, pk: str, sk: str, value: str) -> None: ...
    def load_model(self, pk: str, sk: str) -> str: ...
